server:
  port: 80
  database: /config/filebrowser/data/filebrowser.db
  sources:
    - path: /srv
      config:
        defaultEnabled: true
auth:
  methods:
    noauth: true
frontend:
  name: "KDLHOST: File Browser"