---
name: "Simple Checks"

on:
  workflow_call:

jobs:
  metadata-validation:
    name: Validate Image Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Collect changed files
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: filter
        with:
          list-files: shell
          filters: |
            cue:
              - added|modified: "apps/**/metadata.yaml"
              - added|modified: "apps/**/metadata.json"
              - added|modified: "./metadata.rules.cue"

      - name: Setup CUE
        if: ${{ steps.filter.outputs.cue == 'true' }}
        uses: cue-lang/setup-cue@1713281ae501e533ff06108005dffeab9e2e5203 # v1.0.0

      # Run against all files to ensure they are tested if the cue schema is changed.
      - name: Validate image metadata
        if: ${{ steps.filter.outputs.cue == 'true' }}
        shell: bash
        run: |
          find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./metadata.rules.cue
          find ./apps/ -name metadata.yaml | xargs -I {} cue vet --schema '#Spec' {} ./metadata.rules.cue
